### ISSUE TITLE
RAM usage issues

### ISSUE THREAD

**Issue by AaronGeorge** [x43x61x69/Metarminator#12]
Hey @x43x61x69,

I've noticed that when batch removing tags with multiple files it hammers my RAM usage like no other. Is there any way to have it do one file and then dump the memory before it starts the other? Is there a command line way of allowing this to happen if you don't have time to add it to the app?

**Comment by x43x61x69** [comment]
Hi @AaronGeorge ,

Sorry for the late reply. Was busy with hospital and school.

The file processing is done with threading, which make sure it can be done ASAP. It could take REALLY long if you disable the threading. Normally, the processing should be done within seconds on an Air for a few dozens of .m4a(s) so it shouldn't be a problem. Each thread is standalone, once that thread is finished processing, it writes to the disk by itself, not all at once.

Best,
Cai
